stages:
  - build
  - test

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: dev
  paths:
    - .npm
    - client/node_modules
    - e2e/node_modules
    - cache/Cypress

# this job installs NPM dependencies and Cypress
install_cy:
  image: cypress/base:10
  stage: build

  script:
    - cd e2e
    - yarn install
    - yarn run cypress:verify

build_client:
  stage: build
  image: 'node:12.6-alpine'
  script:
    - cd client
    - yarn install

test_app:
  only:
    - dev
  image: 'node:12.6-alpine'
  stage: test
  script:
    - cd client
    - yarn run test

# all jobs that actually run tests can use the same definition
test_e2e:
  image: cypress/base:10
  only:
    - dev
  stage: test
  script:
    - cd e2e
    - yarn run test

after_script:
  - rm -rf .npm
  - rm -rf client/node_modules
  - rm -rf e2e/node_modules
  - rm -rf cache/Cypress
# # actual job definitions
# # all steps are the same, they come from the template above
# electrons-1:
#   <<: *job
# electrons-2:
#   <<: *job
# electrons-3:
#   <<: *job
# electrons-4:
#   <<: *job
# electrons-5:
#   <<: *job
