stages:
  - build
  - test

# variables:
#   npm_config_cache: '$CI_PROJECT_DIR/.npm'
#   CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

# # cache using branch name
# # https://gitlab.com/help/ci/caching/index.md
# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#     - .npm
#     - client/node_modules
#     - e2e/node_modules

# this job installs NPM dependencies and Cypress
install_cy:
  image: cypress/base:10
  stage: build

  script:
    - cd e2e
    - yarn install
    - yarn run cypress:verify

test_app:
  image: 'node:12.6'
  stage: test
  script:
    - cd client
    - yarn install
    - yarn run test

# all jobs that actually run tests can use the same definition
test_e2e:
  image: cypress/base:10
  stage: test
  script:
    - cd e2e
    - yarn run cypress:run
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
# # actual job definitions
# # all steps are the same, they come from the template above
# electrons-1:
#   <<: *job
# electrons-2:
#   <<: *job
# electrons-3:
#   <<: *job
# electrons-4:
#   <<: *job
# electrons-5:
#   <<: *job
