version: '3.7'

networks:
  library_local:

volumes:
  local_client: {}
  local_api: {}
  local_postgres_data: {}
  local_postgres_backups: {}

services:
  client:
    build:
      context: .
      dockerfile: ./compose/local/client/Dockerfile
    image: client_local
    restart: always
    volumes:
      - local_client:/client
    env_file:
      - ./.envs/.local/.client
    command: yarn run start
    depends_on:
      - library_postgres
      - books
    networks:
      - library_local
    ports:
      - '3000:3000'

  books:
    build:
      context: .
      dockerfile: ./compose/local/books/Dockerfile
    image: books_local
    command: /start
    restart: always
    depends_on:
      - library_postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.books
      - ./.envs/.local/.redis
    ports:
      - '9000:9000'
    networks:
      - library_local

  redis:
    image: redis:latest

  # api:
  #   build:
  #     context: .
  #     dockerfile: ./compose/production/api/Dockerfile
  #   image: api_local
  #   command: ['yarn', 'start']
  #   # command: ['yarn', 'run', 'start']
  #   networks:
  #     - library_local
  #   ports:
  #     - '9000:9000'
  #   volumes:
  #     - local_api:/api
  #   depends_on:
  #     - library_postgres
  #   env_file:
  #     - ./.envs/.local/.postgres
  #     - ./.envs/.local/.api
  #     - ./.envs/.local/.client

  library_postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    healthcheck:
      test: ['CMD', 'sh', '-c', '/usr/local/bin/healthcheck']
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    expose:
      - '5432'
    image: library_local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - library_local
