version: '3.7'

networks:
  biblioteca_local:

services:
  client:
    build:
      context: .
      dockerfile: ./compose/local/client/Dockerfile
    image: client_local
    command: ['yarn', 'run', 'start']
    env_file:
      - ./.envs/.local/.client
    ports:
      - '3000:3000'
    networks:
      - biblioteca_local
