version: '2'

services:
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - TRAEFIK_ROOT/traefik.toml:/traefik.toml
      - TRAEFIK_ROOT/acme.json:/acme.json
    container_name: traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=8080'
      - 'traefik.backend.healthcheck.interval=10s'

networks:
