#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


/wait-for $POSTGRES_HOST:$POSTGRES_PORT -t 120 -- /migrate \
    -database "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB?sslmode=$POSTGRES_SSLMODE" \
    -path $MIGRATIONS_DIR \
    up

exec "$@"
